# Generated by Django 4.1.4 on 2023-01-08 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('amount', models.IntegerField()),
                ('date', models.DateField()),
                ('category', models.CharField(max_length=32)),
                ('type', models.CharField(max_length=16)),
            ],
        ),
    ]
