# Generated by Django 4.1.4 on 2023-01-15 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('amount', models.IntegerField()),
                ('mobile', models.CharField(max_length=16)),
                ('type', models.CharField(max_length=16)),
            ],
        ),
    ]
